# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '90s' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 90s
 pod 'SnapKit', '~> 5.0.0'
 pod 'RxSwift' 
 pod 'RxCocoa'
 pod 'RxDataSources', '~> 4.0'
 pod 'RxAlamofire'
 pod 'RealmSwift'
 pod 'SwiftLint'
 pod 'Moya'

 pod 'KakaoSDK'
 pod 'RxKakaoSDKCommon'
 pod 'KakaoSDKAuth'
 pod 'RxKakaoSDKAuth'
 pod 'KakaoSDKUser'
 pod 'RxKakaoSDKUser'
 
 
end
